openapi: 3.0.0
servers:
  - url: http://localhost:8080/v1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jlgula/Polaris/1.0.0
info:
  version: 1.0.0
  title: "Polaris"
  description: "Microgrid controller"
  contact:
    email: jlgula@papugh.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: device
    description: "Devices managed by the controller"
paths:
  /devices/reset:
    post:
      tags:
        - device
      summary: Resets the GC
      description: Removes all devices and resets the GC.
      operationId: reset
      x-scala-package: device
      responses:
        "201":
          description: "Devices reset"
          content:
            text/plain:
              schema:
                type: string
  /devices:
    get:
      tags:
        - device
      summary: Lists devices
      description: Gets a list of all known devices
      operationId: listDevices
      x-scala-package: device
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
    post:
      tags:
        - device
      summary: Adds a device
      description: Adds a new device to the list of all known device
      operationId: addDevice
      x-scala-package: device
      requestBody:
        required: true
        content:
          #          application/x-www-form-urlencoded:
          #            schema:
          #              properties:
          #                name:
          #                  type: string
          #                status:
          #                  type: string
          #              required:
          #                - name
          #          multipart/form-data:
          #            schema:
          #              properties:
          #                name:
          #                  type: string
          #                status:
          #                  type: string
          #                file:
          #                  type: string
          #                  format: binary
          #              required:
          #                - name
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
      responses:
        "201":
          description: "Device successfully added"
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
  /devices/{id}:
    get:
      tags:
        - device
      operationId: getDevice
      x-scala-package: device
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "Get successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        "404":
          description: Not found - the id does not corresponed to a registered device
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - device
      operationId: putDevice
      x-scala-package: device
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
      responses:
        "204":
          description: "Update successful, no content returned"
        "400":
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: Not found - the id does not corresponed to a registered device
          content:
            text/plain:
              schema:
                type: string
  /devices/{id}/powerGranted:
    get:
      tags:
        - device
      operationId: getPowerGranted
      x-scala-package: device
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "Get successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PowerGranted"
        "404":
          description: Not found - the id does not corresponed to a registered device
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - device
      operationId: putPowerGranted
      x-scala-package: device
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PowerGranted"
      responses:
        "204":
          description: "Update successful, no content returned"
        "400":
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: Not found - the id does not corresponed to a registered device
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Device:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: string
        name:
          type: string
        powerRequested:
          type: number
          description: the power that the device needs in watts to perform its primary function
    PowerGranted:
      description: the power that the device has been granted in watts
      type: number
