name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16' ]
        scala: [
            { version: '2.13.6', bincompat: '2.13.6' }
          ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: print Java version
      run: java -version
    - uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-scala-${{ matrix.scala.version }}-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-scala-${{ matrix.scala.version }}-
    - name: Run tests
      run:  sbt ++${{ matrix.scala.version }} clean test:compile
